pop_up = "//div[@class='ecomsend__Modal__CloseButton _closeBtn_4tu8s_236']"
pendents = "//div[@class='navigation']/ul/li[1]/a"
search_result = "//div[@id='gf-products']/DIV[1]/DIV[1]/DIV[1]/A[1]/IMG[1]"
add_to_cart = "//input[@value='Add to Cart']"
select_size = "//div[@id='option-box-1tem1']/DIV[2]/SPAN[1]"
checkout = "//input[@name='checkout' and @id='checkout']"
email = "//input[@id='email' and @name='email']"
first_name = "//input[@id='TextField0' and @name='firstName']"
last_name = "//input[@id='TextField1' and @name='lastName']"
address = "//input[@id='shipping-address1' and @name='address1']"
city = "//input[@id='TextField3' and @name='city']"
state = "//select[@name='zone' and @id='Select1']"
pin = "//input[@id='TextField4' and @name='postalCode']"
phone = "//input[@id='TextField5' and @name='phone']"
save_shipping_information_checkbox = "//input[@id='save_shipping_information' and @name='save_shipping_information']"
sms_marketing_opt_in_check_box = "//input[@id='sms_marketing_opt_in' and @name='sms_marketing_opt_in']"
return_to_cart = "//form[@id='Form0']/DIV[1]/DIV[1]/DIV[1]/DIV[2]/DIV[1]/DIV[2]/DIV[2]/A[1]"
continue_shopping = "//form[@id='Form0']/DIV[1]/DIV[1]/DIV[1]/DIV[2]/DIV[1]/DIV[2]/DIV[1]/BUTTON[1]"



